name: NovaCoreGameEngine
main: net.zeeraa.novacore.spigot.gameengine.NovaCoreGameEngine
description: Novacores basic game engine
version: 2.0.0
api-version: 1.13
depend: [NovaCore]

permissions:
  novacore.gamelobby.forcemap:
    description: Allow force selecting maps
    default: op